before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/actdocs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: git

dockers:
  - image_templates:
      - "tmknom/actdocs:{{ .Tag }}-amd64"
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"
      - "--platform=linux/amd64"
  - image_templates:
      - "tmknom/actdocs:{{ .Tag }}-arm64"
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "tmknom/actdocs:{{ .Tag }}"
    image_templates:
      - "tmknom/actdocs:{{ .Tag }}-amd64"
      - "tmknom/actdocs:{{ .Tag }}-arm64"
  - name_template: "tmknom/actdocs:latest"
    image_templates:
      - "tmknom/actdocs:{{ .Tag }}-amd64"
      - "tmknom/actdocs:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/tmknom/actdocs:{{ .Tag }}"
    image_templates:
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-amd64"
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/tmknom/actdocs:latest"
    image_templates:
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-amd64"
      - "ghcr.io/tmknom/actdocs:{{ .Tag }}-arm64"
